---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    D: true
    vv: true

lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos_7
    image: centos:7
    dockerfile: /opt/jenkins_agent/workspace/freestyle/vector-role/resources/Dockerfile.j2
    # pre_build_image: true
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
  options:
    vv: false
    D: true
  inventory:
    links:
      hosts: /opt/jenkins_agent/workspace/freestyle/vector-role/resources/inventory/hosts.yml
      group_vars: /opt/jenkins_agent/workspace/freestyle/vector-role/resources/inventory/group_vars/
      host_vars: /opt/jenkins_agent/workspace/freestyle/vector-role/resources/inventory/host_vars/
  playbooks:
    converge: /opt/jenkins_agent/workspace/freestyle/vector-role/resources/playbooks/converge.yml
verifier:
  name: ansible
  playbooks:
    verify: /opt/jenkins_agent/workspace/freestyle/vector-role/resources/tests/verify.yml
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify