---
- name: Create folder for Vector
  become: true
  file:
    state: directory
    path: "/opt/vector"
    mode: 0755
- name: Download Vector achive
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "~/"
    mode: 0755
- name: Extract vector and start
  become: true
  unarchive:
      copy: false
      src: "~/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "/opt/vector"
      extra_opts: [--strip-components=2]
      mode: 0755
- name: Set environment vector
  become: true
  template:
      src: templates/vec.sh.j2
      dest: /etc/profile.d/vec.sh
- name: Copy congif vector
  become: true
  template:
      src: templates/vector.toml.j2
      dest: /opt/vector/config/vector.toml
- name: Start Vector
  become: true
  shell: |
    echo -e "[Service]\n \
    ExecStart=/opt/vector/bin/vector --config /opt/vector/config/vector.toml\n \
    Restart=always" > /etc/systemd/system/vector.service
    systemctl daemon-reload
    systemctl start vector.service
